name: Project Test

on:
  pull_request:
    branches:
    - master
    - develop
  push:
    branches:
    - master
    paths:
    - 'app.py'
    - 'pytest.ini'
    - 'src/**/*'
    - 'tests/**/*'

jobs:
  test:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install loguru pyyaml pandas
          pip install pytest pytest-cov pytest-mock
      
      - name: Run project tests
        run: python -m pytest tests/ --cov --cov-report term-missing